// Barrel export for src/bridge/

export type {
  AgentEvent,
  AgentHandle,
  AgentToolDescriptor,
  AgentToolPermission,
  AgentToolProvenance,
  BridgeError,
  BridgeRequestAbandonPayload,
  BridgeResourceClaimPayload,
  BridgeRpcErrorCode,
  BrowserToolInvokeResult,
  CallOptions,
  ChatToolResultOptions,
  ChatContent,
  ChatEvent,
  ChatMessage,
  ChatSessionOpts,
  ChatToolCall,
  ComposerDraft,
  ComposerDraftScope,
  ConversationActiveSessionsError,
  ConversationBulkResponse,
  ConversationBulkResult,
  ConversationListOptions,
  ConversationListState,
  ConversationMeta,
  ConversationProject,
  ConversationProjectMoveResult,
  CostEstimate,
  HapticStyle,
  KeyValidationResult,
  MahoBridge,
  PhotoCapture,
  PinchSummaryEvent,
  Platform,
  Provider,
  RpcRequest,
  RpcResponse,
  SessionHandle,
  SpaceAIConfig,
  ToolCallRecord,
  ToolDefinition,
  ToolResult,
} from './types';

export { callBridge, call, disposeDocumentBridge, isBridgeRpcError, detectPlatform } from './rpc';
export { subscribeStream, subscribeStreamWithCadence } from './streaming';
export type { ImageDelta, StreamSubscriber, ToolCallDelta } from './streaming';
