import {MojoKeyCombo, ShortcutBinding} from '../../mojo.js';

export type ShortcutActionId =
  | 'command_bar'
  | 'command_bar_alt'
  | 'focus_url_bar'
  | 'copy_url'
  | 'open_history'
  | 'open_downloads'
  | 'new_space'
  | 'go_back'
  | 'go_forward'
  | 'reload_tab'
  | 'hard_reload'
  | 'stop_loading'
  | 'new_tab'
  | 'close_tab'
  | 'restore_tab'
  | 'pin_tab'
  | 'duplicate_tab'
  | 'next_tab'
  | 'prev_tab'
  | 'select_tab_1'
  | 'select_tab_2'
  | 'select_tab_3'
  | 'select_tab_4'
  | 'select_tab_5'
  | 'select_tab_6'
  | 'select_tab_7'
  | 'select_tab_8'
  | 'select_tab_last'
  | 'toggle_sidebar'
  | 'ai_panel'
  | 'find_in_page'
  | 'zoom_in'
  | 'zoom_out'
  | 'reset_zoom'
  | 'view_source'
  | 'print_page'
  | 'settings'
  | 'maho_mini'
  | 'next_space'
  | 'prev_space'
  | 'select_space_1'
  | 'select_space_2'
  | 'select_space_3'
  | 'select_space_4'
  | 'select_space_5'
  | 'select_space_6'
  | 'select_space_7'
  | 'select_space_8'
  | 'select_space_last'
  | 'add_split_view'
  | 'add_split_view_arc'
  | 'increase_split_view'
  | 'decrease_split_view'
  | 'remove_split_view'
  | 'next_split_view'
  | 'prev_split_view'
  | 'swap_split_view';

export interface ShortcutBindingEx extends ShortcutBinding {
  action: ShortcutActionId;
}
