// Generated by generate_update_pubkey.py. DO NOT EDIT.
#ifndef MAHO_UPDATE_MANIFEST_PUBLIC_KEY_H_
#define MAHO_UPDATE_MANIFEST_PUBLIC_KEY_H_

#include <array>
#include <cstdint>

namespace maho {
namespace updates {

inline constexpr std::array<uint8_t, 32> kMahoUpdateManifestPublicKey = {
    0x8b, 0x07, 0x6b, 0x75, 0xcb, 0x78, 0x96, 0x81, 0x09, 0x97, 0xc5, 0x9b, 0x1e, 0xc7, 0xe1, 0x84, 0x73, 0x0d, 0x71, 0x4c, 0xa0, 0x67, 0x9e, 0x0d, 0xea, 0xe2, 0x2f, 0x7a, 0xba, 0x0d, 0x4d, 0xbc};

inline constexpr bool kMahoUpdateManifestPublicKeyIsPlaceholder = false;

}  // namespace updates
}  // namespace maho

#endif  // MAHO_UPDATE_MANIFEST_PUBLIC_KEY_H_
