# Copyright 2026 Maho Browser. All rights reserved.

source_set("maho_split_view") {
  sources = [
    "maho_split_view_controller.cc",
    "maho_split_view_controller.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/browser/ui/tabs:tab_strip",
    "//components/split_tabs",
    "//content/public/browser",
    "//ui/base",
    "//url",
  ]
}
