# Copyright 2026 Maho Browser. All rights reserved.

source_set("interactive_tests") {
  testonly = true

  sources = [ "maho_shield_bubble_interactive_uitest.cc" ]

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  deps = [
    ":shields",
    "//base",
    "//base/test:test_support",
    "//chrome/browser",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/views/frame",
    "//chrome/browser/ui/views/page_info",
    "//chrome/browser/ui/views/toolbar",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//content/public/browser",
    "//content/test:test_support",
    "//maho/browser/ui/site_control:maho_site_control",
    "//net:test_support",
    "//testing/gtest",
    "//ui/base",
    "//ui/views",
    "//ui/views:test_support",
    "//url",
  ]
}

source_set("shields") {
  sources = [
    "maho_shield_bubble_coordinator.cc",
    "maho_shield_bubble_coordinator.h",
    "maho_shield_bubble_view.cc",
    "maho_shield_bubble_view.h",
  ]
  deps = [
    "//base",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/tabs:tab_strip",
    "//content/public/browser",
    "//maho/browser:maho_core_holder",
    "//maho/browser:maho_settings_navigation",
    "//maho/browser/net",
    "//maho/third_party/maho:maho_bridge",
    "//ui/base",
    "//ui/color",
    "//ui/gfx",
    "//ui/views",
    "//url",
  ]
}
