package dev.maho.browser.ui.icons

import androidx.annotation.DrawableRes
import dev.maho.browser.R

enum class MahoIcon(@DrawableRes val drawableRes: Int) {
    NavBack(R.drawable.ic_chevron_left),
    NavForward(R.drawable.ic_chevron_right),
    Close(R.drawable.ic_x),
    ReloadSync(R.drawable.ic_rotate_cw),
    Search(R.drawable.ic_search),
    Copy(R.drawable.ic_copy),
    Bot(R.drawable.ic_bot),
    Globe(R.drawable.ic_globe),
    Downloads(R.drawable.ic_download),
    Archive(R.drawable.ic_clock),
    Spaces(R.drawable.ic_layout_grid),
    Boosts(R.drawable.ic_sparkles),
    Notes(R.drawable.ic_notebook_text),
    Bookmarks(R.drawable.ic_bookmark),
    History(R.drawable.ic_history),
    ReadingList(R.drawable.ic_eye),
    Settings(R.drawable.ic_settings),
    Profiles(R.drawable.ic_circle_user),
    Notifications(R.drawable.ic_bell),
    AutofillKey(R.drawable.ic_key_round),
    Privacy(R.drawable.ic_shield),
    HelpFeedback(R.drawable.ic_message_square),
    ClearSweep(R.drawable.ic_trash_2),
    Delete(R.drawable.ic_trash_2),
    Share(R.drawable.ic_share),
    MoreActions(R.drawable.ic_ellipsis_vertical),
    InfoLock(R.drawable.ic_lock),
    SparklesAi(R.drawable.ic_sparkles),
    Add(R.drawable.ic_plus),
    CheckCircle(R.drawable.ic_circle_check),
    ExpandMore(R.drawable.ic_chevron_down),
    Filter(R.drawable.ic_list_filter),
    Folder(R.drawable.ic_folder),
    Launch(R.drawable.ic_arrow_up_right),
    SearchAlt(R.drawable.ic_search),

    Palette(R.drawable.ic_palette),
    SyncIcon(R.drawable.ic_refresh_cw),
    Book(R.drawable.ic_book_open),
    Star(R.drawable.ic_star),
    Tune(R.drawable.ic_sliders_horizontal),
    Code(R.drawable.ic_code),
    RestartAlt(R.drawable.ic_rotate_ccw),

    Mic(R.drawable.ic_mic),
    MicOff(R.drawable.ic_mic_off),
    Eye(R.drawable.ic_eye),
    EyeOff(R.drawable.ic_eye_off),
    VisibilityOff(R.drawable.ic_eye_off),
    Warning(R.drawable.ic_triangle_alert),
    DragHandle(R.drawable.ic_grip_horizontal),
    Play(R.drawable.ic_play),
    Pause(R.drawable.ic_pause),
    Camera(R.drawable.ic_camera),
    MapPin(R.drawable.ic_map_pin),
    Moon(R.drawable.ic_moon),
    Sun(R.drawable.ic_sun),
    Minus(R.drawable.ic_minus),
    Check(R.drawable.ic_check),
    CircleAlert(R.drawable.ic_circle_alert),
    Cloud(R.drawable.ic_cloud),
    CloudOff(R.drawable.ic_cloud_off),
    Monitor(R.drawable.ic_monitor),
    Smartphone(R.drawable.ic_smartphone),
    TabletSmartphone(R.drawable.ic_tablet_smartphone),
    Send(R.drawable.ic_send),
    Link(R.drawable.ic_link),
    ZoomIn(R.drawable.ic_zoom_in),
    ZoomOut(R.drawable.ic_zoom_out),
    PictureInPicture(R.drawable.ic_picture_in_picture_2),
    ChevronRight(R.drawable.ic_chevron_right),
    Clock(R.drawable.ic_clock),
    BookmarkBorder(R.drawable.ic_bookmark),
    Tab(R.drawable.ic_layout_grid),
    ListX(R.drawable.ic_list_x),
    Eraser(R.drawable.ic_eraser);
}
